import {Barlow_Condensed, Raleway} from "next/font/google";
import {Header} from "@/components/custom/Header";
import ProductProvider from "@/context/ProductProvider";
import "./globals.css";

const barlow = Barlow_Condensed({
    subsets: ["latin"],
    weight: ["300", "700"],
    style: ['normal', 'italic']
});

const raleway = Raleway({
    subsets: ["latin"],
    weight: ["300", "700", "900"],
    style: ['normal', 'italic']
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <ProductProvider>
        <body className={`${barlow.className} ${raleway.className}`}>
            <Header/>
            {children}
        </body>
    </ProductProvider>
    </html>
  );
}
